const express = require("express");
const router = express.Router();
const MainController = require("../controllers/MainController");
const auth = require("../middlewares/auth");
router.get("/", MainController.redirecionamento);
router.get("/login", MainController.login);
router.get("/cadastre-se", MainController.cadastro);
router.get("/sucesso", auth, MainController.sucesso);
router.post("/login", MainController.fazerLogin);
router.post("/cadastre-se", MainController.fazerCadastro);
module.exports = router;
