const express = require("express");
const router = express.Router();
const MainController = require("../controllers/MainController");
const auth = require("../middlewares/auth");
router.get("/", MainController.redirecionamento);
router.get("/login", auth.login, MainController.login);
router.get("/cadastre-se", auth.login, MainController.cadastro);
router.get("/sucesso", auth.verificar, MainController.sucesso);
router.post("/login", MainController.fazerLogin);
router.post("/cadastre-se", MainController.fazerCadastro);
router.post("/sair", MainController.logout);
module.exports = router;
