const express = require("express");
const router = express.Router();
const MainController = require("../controllers/MainController");
const auth = require("../middlewares/auth");
router.get("/", MainController.redirect);
router.get("/login", auth.login, MainController.login);
router.get("/cadastre-se", auth.login, MainController.register);
router.get("/sucesso", auth.verify, MainController.sucess);
router.post("/login", MainController.signIn);
router.post("/cadastre-se", MainController.signUp);
router.post("/sair", MainController.logout);
module.exports = router;
